let playW = () => new Audio("sounds/crash.mp3").play()
let playA = () => new Audio("sounds/kick-bass.mp3").play()
let playS = () => new Audio("sounds/snare.mp3").play()
let playD = () => new Audio("sounds/tom-1.mp3").play()
let playJ = () => new Audio("sounds/tom-2.mp3").play()
let playK = () => new Audio("sounds/tom-3.mp3").play()
let playL = () => new Audio("sounds/tom-4.mp3").play()
